name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check vagrant
        run: apt list virtualbox -a
      - name: Download vagrant
        run: echo 'Install Vagrant'
      - run: curl -O https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.deb
      - run: sudo apt install ./vagrant_2.2.7_x86_64.deb
      - run: vagrant --version
