name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:

      - name: Update package
        run: sudo apt update

      - name: Check Virtualbox
        run: apt list virtualbox -a
      - name: Install Virtualbox
        run: sudo apt install virtualbox

      - name: Download vagrant
        run: curl -O https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.deb
      - name: Install vagrant
        run: sudo apt install ./vagrant_2.2.7_x86_64.deb
      - name: Check vagrant version
        run: vagrant --version

      # - name: Wakeup vagrant
      # run: vagrant up
      
      - name: テストpwd 
        run: |
          pwd

      - name: テストls-la
        run: |
          ls -la
      - name: テストls-la ../
        run: |
          ls -la ../
      - name: テストls-la ../../
        run: |
          ls -la ../../
      - name: テストls-la ../../../
        run: |
          ls -la ../../../
